"use client";

import { useState } from "react";
import { Icon } from "@/components/Icon";

export function SignInDialog() {
  const [open, setOpen] = useState(false);
  const [mode, setMode] = useState<"signin" | "create">("signin");
  const [notice, setNotice] = useState("");
  function openDialog() { setNotice(""); setOpen(true); }
  function switchMode(next: "signin" | "create") { setNotice(""); setMode(next); }
  return <><button type="button" className="header-signin" onClick={openDialog}><Icon name="lock" size={17} /> Sign in</button>
    {open && <div className="modal-backdrop"><section className="signin-dialog" role="dialog" aria-modal="true" aria-labelledby="signin-title"><button className="modal-close" type="button" onClick={() => setOpen(false)} aria-label="Close sign in"><Icon name="close" size={20}/></button>{notice ? <div className="signin-confirm"><span><Icon name="check" size={23}/></span><h2>Thanks for trying Kelus.</h2><p>{notice}</p><button className="button button-primary" type="button" onClick={() => setOpen(false)}>Done</button></div> : <><p className="eyebrow">Welcome to Kelus</p><h2 id="signin-title">{mode === "signin" ? "Sign in to your account" : "Create your Kelus account"}</h2><p className="dialog-copy">Save price alerts and keep your shopping decisions in one place.</p><div className="signin-tabs"><button className={mode === "signin" ? "active" : ""} onClick={() => switchMode("signin")}>Sign in</button><button className={mode === "create" ? "active" : ""} onClick={() => switchMode("create")}>Create account</button></div><form onSubmit={(event) => { event.preventDefault(); setNotice(mode === "signin" ? "You are signed in for this demo. No account details were stored." : "Your demo account is ready. No account details were stored."); }}><label>Email address<input type="email" placeholder="you@example.com" autoComplete="email" required/></label><label>Password<input type="password" placeholder="••••••••" autoComplete={mode === "signin" ? "current-password" : "new-password"} required/></label>{mode === "signin" && <button className="forgot-link" type="button" onClick={() => setNotice("Password reset is not enabled in this demo.")}>Forgot password?</button>}<button className="button button-primary dialog-submit" type="submit">{mode === "signin" ? "Sign in" : "Create account"}<Icon name="arrow" size={17}/></button></form><div className="dialog-divider"><span>or continue with</span></div><div className="social-buttons"><button type="button" onClick={() => setNotice("Google sign-in will be available in the live product.")}><b>G</b>Google</button><button type="button" onClick={() => setNotice("Apple sign-in will be available in the live product.")}><b>●</b>Apple</button></div><p className="dialog-legal">Demo sign-in only — no account or password is stored.</p></>}</section></div>}</>;
}
