create table if not exists public.price_observations (
  id bigint generated by default as identity primary key,
  canonical_product_id text not null,
  variant_id text not null,
  provider_id text not null,
  retailer_id text not null,
  offer_id text not null,
  price_cents integer not null check (price_cents >= 0),
  shipping_cents integer check (shipping_cents is null or shipping_cents >= 0),
  currency text not null check (currency = 'USD'),
  condition text not null check (condition in ('new', 'used', 'refurbished')),
  availability text not null,
  observed_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (provider_id, offer_id, observed_at)
);

create index if not exists price_observations_product_variant_condition_time_idx
on public.price_observations(canonical_product_id, variant_id, condition, observed_at desc);

alter table public.price_observations enable row level security;

-- Observations are operational provider data. Browser roles cannot read or
-- write them; only the server-side Supabase service role has access.
revoke all on table public.price_observations from anon, authenticated;
