create table if not exists public.price_alert_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  user_id uuid not null,
  alert_id text not null,
  event_type text not null check (event_type in ('price_drop', 'target_reached')),
  event_data jsonb not null,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),
  foreign key (user_id, alert_id) references public.price_alerts(user_id, id) on delete cascade
);

create index if not exists price_alerts_updated_at_idx on public.price_alerts(updated_at);
create index if not exists price_alert_events_user_time_idx on public.price_alert_events(user_id, occurred_at desc);

alter table public.price_alert_events enable row level security;

revoke all on table public.price_alert_events from anon, authenticated;
grant select on table public.price_alert_events to authenticated;

drop policy if exists "Users can read only their own alert events" on public.price_alert_events;
create policy "Users can read only their own alert events"
on public.price_alert_events for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;

select cron.unschedule(jobid)
from cron.job
where jobname = 'kelus-price-alert-monitor';

select cron.schedule(
  'kelus-price-alert-monitor',
  '17 */6 * * *',
  $monitor$
  select net.http_post(
    url := 'https://kelus.me/api/alerts/check',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || (
        select decrypted_secret
        from vault.decrypted_secrets
        where name = 'kelus_alert_monitor_secret'
        limit 1
      )
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 120000
  )
  where exists (
    select 1 from vault.decrypted_secrets where name = 'kelus_alert_monitor_secret'
  );
  $monitor$
);
